title: Wally Yang - Production Engineer
email: wallyyang28@gmail.com
tagline: Production Engineer, using Linux between Chaotic good and Lawful evil
description: >- # this means to ignore newlines until "baseurl:"
  Production Engineer, using Linux between Chaotic good and Lawful evil
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  WallyYang

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap

remote_theme: jekyll/minima

header_pages:
  - index.md
  - blogs.md
  - resume.md

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
